# run a node.js script to use code from semantic-release
after_success:
  - semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --disable-snapshot-skip-ci
  # The following line is optional in maven-semantic-release projects.
  # It is included here to test running code coverage reports as part of conveyal workflow.
  # run codecov after semantic-release because maven-semantic-release creates extra commits that
  # codecov will need a report on to reference in future PRs to the release branch
  - bash <(curl -s https://codecov.io/bash)
before_install: |
  echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch
# install dependencies used in after_success here because they don't get cached if called in after_success
before_script:
  # install node 14
  - nvm install '14'
  - nvm use 14
  - yarn global add @conveyal/maven-semantic-release semantic-release
cache:
  directories:
    - $HOME/.m2
    - $HOME/.yarn-cache
    - $HOME/.cache/yarn
install: true
jdk:
  - openjdk8
language: java
notifications:
  email: false
script:
  - mvn package
os: linux
