/*
 * Webservices API
 * Endpoints documentation and sandbox
 *
 * OpenAPI spec version: 2.0.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fr.redfroggy.ilg.client.authentication;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AuthenticationJwt
 */
public class AuthenticationJwt {

  private final String token;

  private final String refreshToken;

  public AuthenticationJwt(@JsonProperty("token") String token, @JsonProperty("refresh_token") String refreshToken) {
    this.token = token;
    this.refreshToken = refreshToken;
  }

   /**
   * Get token
   * @return token
  **/
  public String getToken() {
    return token;
  }

   /**
   * Get refreshToken
   * @return refreshToken
  **/
  public String getRefreshToken() {
    return refreshToken;
  }

}

