/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package fr.redfroggy.ilg.client.openapi.api;

import fr.redfroggy.ilg.client.openapi.model.Error400Model;
import fr.redfroggy.ilg.client.openapi.model.Error401Model;
import fr.redfroggy.ilg.client.openapi.model.Error403Model;
import fr.redfroggy.ilg.client.openapi.model.ErrorModel;
import fr.redfroggy.ilg.client.openapi.model.Legal;
import fr.redfroggy.ilg.client.openapi.model.LegalDepositList;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "LegalInformation", description = "the LegalInformation API")
public interface LegalInformationApi {

    /**
     * GET /companies/{country}/{id}/legal/deposits/{depositId} : Get legal deposit files as PDF
     *
     * @param id Unique identifier representing a specific company (required)
     * @param country Country Code in ISO 3166-2 (required)
     * @param depositId Document id, can be found in deposit list (required)
     * @return PDF Datastream (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "Get legal deposit files as PDF", nickname = "companiesCountryIdLegalDepositsDepositIdGet", notes = "", authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Legal information", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "PDF Datastream"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/companies/{country}/{id}/legal/deposits/{depositId}",
        produces = "application/pdf,text/plain", 
        method = RequestMethod.GET)
    ResponseEntity<Void> companiesCountryIdLegalDepositsDepositIdGet(@ApiParam(value = "Unique identifier representing a specific company",required=true) @PathVariable("id") String id,@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Country Code in ISO 3166-2",required=true) @PathVariable("country") String country,@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Document id, can be found in deposit list",required=true) @PathVariable("depositId") String depositId);


    /**
     * GET /companies/{country}/{id}/legal/deposits : List of legal file deposit
     *
     * @param id Unique identifier representing a specific company (required)
     * @param country Country Code in ISO 3166-2 (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "List of legal file deposit", nickname = "companiesCountryIdLegalDepositsGet", notes = "", response = LegalDepositList.class, authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Legal information", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = LegalDepositList.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/companies/{country}/{id}/legal/deposits",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<LegalDepositList> companiesCountryIdLegalDepositsGet(@ApiParam(value = "Unique identifier representing a specific company",required=true) @PathVariable("id") String id,@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Country Code in ISO 3166-2",required=true) @PathVariable("country") String country);


    /**
     * GET /companies/{country}/{id}/legal : All legal information
     *
     * @param id Unique identifier representing a specific company (required)
     * @param country Country Code in ISO 3166-2 (required)
     * @param column Column name in JSONPath format (start with &#39;$.&#39;) for sorting (optional)
     * @param order Sorting order, &#39;asc&#39; or &#39;desc&#39; (optional)
     * @return Legal information (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "All legal information", nickname = "companiesCountryIdLegalGet", notes = "", response = Legal.class, authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Legal information", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Legal information", response = Legal.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/companies/{country}/{id}/legal",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Legal> companiesCountryIdLegalGet(@ApiParam(value = "Unique identifier representing a specific company",required=true) @PathVariable("id") String id,@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Country Code in ISO 3166-2",required=true) @PathVariable("country") String country,@Pattern(regexp="/^\\$\\./") @ApiParam(value = "Column name in JSONPath format (start with '$.') for sorting") @Valid @RequestParam(value = "column", required = false) String column,@ApiParam(value = "Sorting order, 'asc' or 'desc'", allowableValues = "asc, desc") @Valid @RequestParam(value = "order", required = false) String order);


    /**
     * GET /companies/{country}/{id}/legal/status : Get legal status as PDF
     *
     * @param id Unique identifier representing a specific company (required)
     * @param country Country Code in ISO 3166-2 (required)
     * @param date Date of the last status update, can be found in deposit list (optional)
     * @return PDF Datastream (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "Get legal status as PDF", nickname = "companiesCountryIdLegalStatusGet", notes = "", authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Legal information", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "PDF Datastream"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/companies/{country}/{id}/legal/status",
        produces = "application/pdf,text/plain", 
        method = RequestMethod.GET)
    ResponseEntity<Void> companiesCountryIdLegalStatusGet(@ApiParam(value = "Unique identifier representing a specific company",required=true) @PathVariable("id") String id,@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Country Code in ISO 3166-2",required=true) @PathVariable("country") String country,@ApiParam(value = "Date of the last status update, can be found in deposit list") @Valid @RequestParam(value = "date", required = false) String date);

}
