/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package fr.redfroggy.ilg.client.openapi.api;

import fr.redfroggy.ilg.client.openapi.model.Error400Model;
import fr.redfroggy.ilg.client.openapi.model.Error401Model;
import fr.redfroggy.ilg.client.openapi.model.Error403Model;
import fr.redfroggy.ilg.client.openapi.model.ErrorModel;
import fr.redfroggy.ilg.client.openapi.model.Group;
import fr.redfroggy.ilg.client.openapi.model.Links;
import fr.redfroggy.ilg.client.openapi.model.Shareholders;
import fr.redfroggy.ilg.client.openapi.model.Subsidiaries;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "OwnershipRelations", description = "the OwnershipRelations API")
public interface OwnershipRelationsApi {

    /**
     * GET /companies/{country}/{id}/links : Return links members information for a given company
     *
     * @param country Country Code in ISO 3166-2 (required)
     * @param id Unique identifier representing a specific company (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "Return links members information for a given company", nickname = "companiesCountryIdLinksGet", notes = "", response = Links.class, authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Ownership relations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Links.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/companies/{country}/{id}/links",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Links> companiesCountryIdLinksGet(@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Country Code in ISO 3166-2",required=true) @PathVariable("country") String country,@ApiParam(value = "Unique identifier representing a specific company",required=true) @PathVariable("id") String id);


    /**
     * GET /companies/{country}/{id}/links/shareholders : Return shareholders information for a given company
     *
     * @param country Country Code in ISO 3166-2 (required)
     * @param id Unique identifier representing a specific company (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "Return shareholders information for a given company", nickname = "companiesCountryIdLinksShareholdersGet", notes = "", response = Shareholders.class, authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Ownership relations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Shareholders.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/companies/{country}/{id}/links/shareholders",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Shareholders> companiesCountryIdLinksShareholdersGet(@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Country Code in ISO 3166-2",required=true) @PathVariable("country") String country,@ApiParam(value = "Unique identifier representing a specific company",required=true) @PathVariable("id") String id);


    /**
     * GET /companies/{country}/{id}/links/subsidiaries : Return subsidiaries information for a given company
     *
     * @param country Country Code in ISO 3166-2 (required)
     * @param id Unique identifier representing a specific company (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "Return subsidiaries information for a given company", nickname = "companiesCountryIdLinksSubsidiariesGet", notes = "", response = Subsidiaries.class, authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Ownership relations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Subsidiaries.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/companies/{country}/{id}/links/subsidiaries",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Subsidiaries> companiesCountryIdLinksSubsidiariesGet(@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Country Code in ISO 3166-2",required=true) @PathVariable("country") String country,@ApiParam(value = "Unique identifier representing a specific company",required=true) @PathVariable("id") String id);


    /**
     * GET /groups/{id} : Return details for a group
     *
     * @param id Unique identifier representing a group (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "Return details for a group", nickname = "groupsIdGet", notes = "", response = Group.class, authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Ownership relations", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Group.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/groups/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Group> groupsIdGet(@ApiParam(value = "Unique identifier representing a group",required=true) @PathVariable("id") String id);

}
