/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package fr.redfroggy.ilg.client.openapi.api;

import fr.redfroggy.ilg.client.openapi.model.Error400Model;
import fr.redfroggy.ilg.client.openapi.model.Error401Model;
import fr.redfroggy.ilg.client.openapi.model.Error403Model;
import fr.redfroggy.ilg.client.openapi.model.ErrorModel;
import fr.redfroggy.ilg.client.openapi.model.Site;
import fr.redfroggy.ilg.client.openapi.model.Sites;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "Site", description = "the Site API")
public interface SiteApi {

    /**
     * GET /companies/{country}/{id}/sites : Return the site list for a company
     * This service is @Paginable, @Filterable, @Sortable and @Searchable
     *
     * @param country Country Code in ISO 3166-2 (required)
     * @param id Unique identifier representing a specific company (required)
     * @param page Page number (optional)
     * @param number Number of result by page (optional)
     * @param column Column name in JSONPath format (start with &#39;$.&#39;) for sorting (optional)
     * @param order Sorting order, &#39;asc&#39; or &#39;desc&#39; (optional)
     * @param filters Filter parameter in format &#x60;{JsonPath},{value}&#x60; (example: &#x60;$.eventCode,1100&#x60;) (optional, default to new ArrayList&lt;&gt;())
     * @param search Terms to match (optional)
     * @param in Execute match against columns (example : &#x60;$.registrationId&#x60;) (optional, default to new ArrayList&lt;&gt;())
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "Return the site list for a company", nickname = "companiesCountryIdSitesGet", notes = "This service is @Paginable, @Filterable, @Sortable and @Searchable", response = Sites.class, authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Site", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Sites.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/companies/{country}/{id}/sites",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Sites> companiesCountryIdSitesGet(@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Country Code in ISO 3166-2",required=true) @PathVariable("country") String country,@ApiParam(value = "Unique identifier representing a specific company",required=true) @PathVariable("id") String id,@ApiParam(value = "Page number") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Number of result by page") @Valid @RequestParam(value = "number", required = false) Integer number,@Pattern(regexp="/^\\$\\./") @ApiParam(value = "Column name in JSONPath format (start with '$.') for sorting") @Valid @RequestParam(value = "column", required = false) String column,@ApiParam(value = "Sorting order, 'asc' or 'desc'", allowableValues = "asc, desc") @Valid @RequestParam(value = "order", required = false) String order,@ApiParam(value = "Filter parameter in format `{JsonPath},{value}` (example: `$.eventCode,1100`)") @Valid @RequestParam(value = "filters", required = false) List<String> filters,@ApiParam(value = "Terms to match") @Valid @RequestParam(value = "search", required = false) String search,@ApiParam(value = "Execute match against columns (example : `$.registrationId`)") @Valid @RequestParam(value = "in", required = false) List<String> in);


    /**
     * GET /companies/{country}/{id}/sites/{sid} : Return a specific site
     *
     * @param country Country Code in ISO 3166-2 (required)
     * @param id Unique identifier representing a specific company (required)
     * @param sid Unique identifier representing a specific site of the company (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @ApiOperation(value = "Return a specific site", nickname = "companiesCountryIdSitesSidGet", notes = "", response = Site.class, authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "Site", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Site.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error400Model.class),
        @ApiResponse(code = 401, message = "Authentication Failure: Expired Token or Invalid Token", response = Error401Model.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Error403Model.class),
        @ApiResponse(code = 404, message = "Resource not found", response = ErrorModel.class) })
    @RequestMapping(value = "/companies/{country}/{id}/sites/{sid}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Site> companiesCountryIdSitesSidGet(@Pattern(regexp="^[A-Za-z]{2}$") @ApiParam(value = "Country Code in ISO 3166-2",required=true) @PathVariable("country") String country,@ApiParam(value = "Unique identifier representing a specific company",required=true) @PathVariable("id") String id,@ApiParam(value = "Unique identifier representing a specific site of the company",required=true) @PathVariable("sid") String sid);

}
