/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package fr.redfroggy.ilg.client.kyc;

import fr.redfroggy.ilg.client.IlgApi;
import io.swagger.annotations.Api;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.http.ResponseEntity;

@Api(value = "KycCompliance", description = "the KycCompliance API")
@CacheConfig(cacheNames = "ilgKycComplianceApi", cacheResolver = "ilgCacheResolver", keyGenerator = "methodKeyGenerator")
public interface KycComplianceApi extends IlgApi {

    /**
     * GET /companies/{country}/{id}/kyc/ubo : Return a list of ultimate beneficial owners
     *
     * @param country Country Code in ISO 3166-2 (required)
     * @param id Unique identifier representing a specific company (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    @Cacheable
    ResponseEntity<KycUboProjection> getKycUbo(String country, String id);


}
