/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package fr.redfroggy.ilg.client.relation;

import fr.redfroggy.ilg.client.IlgApi;
import io.swagger.annotations.Api;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;

import javax.validation.constraints.Pattern;

@Validated
@Api(value = "OwnershipRelations", description = "the OwnershipRelations API")
public interface OwnershipRelationsApi extends IlgApi {

    /**
     * GET /companies/{country}/{id}/links : Return links members information for a given company
     *
     * @param country Country Code in ISO 3166-2 (required)
     * @param id Unique identifier representing a specific company (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    ResponseEntity<LinksProjection> getLinks(@NotEmpty @Pattern(regexp="^[A-Za-z]{2}$") String country,
                                             @NotEmpty String id);


    /**
     * GET /companies/{country}/{id}/links/shareholders : Return shareholders information for a given company
     *
     * @param country Country Code in ISO 3166-2 (required)
     * @param id Unique identifier representing a specific company (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    ResponseEntity<ShareholdersProjection> getLinksShareholders(@Pattern(regexp="^[A-Za-z]{2}$") String country, String id);


    /**
     * GET /companies/{country}/{id}/links/subsidiaries : Return subsidiaries information for a given company
     *
     * @param country Country Code in ISO 3166-2 (required)
     * @param id Unique identifier representing a specific company (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    ResponseEntity<SubsidiariesProjection> getLinksSubsidiaries(@Pattern(regexp="^[A-Za-z]{2}$") String country,
                                                             String id);


    /**
     * GET /groups/{id} : Return details for a group
     *
     * @param id Unique identifier representing a group (required)
     * @return  (status code 200)
     *         or Bad Request (status code 400)
     *         or Authentication Failure: Expired Token or Invalid Token (status code 401)
     *         or Forbidden (status code 403)
     *         or Resource not found (status code 404)
     */
    ResponseEntity<GroupProjection> getGroups(String id);

}
